### ISSUE TITLE
Change soundfont

### ISSUE THREAD

**Issue by brickhawkins** [homy-game-studio/hgs-unity-tone#21]
Hi, thank you for port this to unity
I want to ask about the SoundFont 
MeltySynth mentioned this code

`// Create the synthesizer.
var sampleRate = 44100;
var synthesizer = new Synthesizer("TimGM6mb.sf2", sampleRate);`

I haven't tried MeltySynth or your library
but is it possible to change SoundFont runtime, and choose the instrument just like you did on the keyboard demo?
I would like to clone Punk o Matic game but using midi

**Comment by MatheusMoura17** [comment]
Hey @brickhawkins, i'm not received notification for this issue, sorry for delay! 

**Tone** contains [GeneralUser GS](https://schristiancollins.com/generaluser.php) SoundFound by convenience. 

To use others you need:

1) Import you SoundFont file to Resources folder and change the extension to `.bytes`
<img width="662" alt="image" src="https://user-images.githubusercontent.com/6765023/195107904-d6d056ed-2a10-4645-8223-a1313b2b97e8.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/6765023/195108212-93b9588f-837f-4d98-886a-277fee4ebafa.png">

2) Create new ScriptableObject:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/6765023/195107042-96f96f5c-e22d-4a77-9252-0c2a4fb48acc.png">

3) Type the location of you SounfFont here
<img width="682" alt="image" src="https://user-images.githubusercontent.com/6765023/195108731-f8ee15d3-ee0e-4166-a811-c372218697d0.png">

4) Finally you can add reference of you SoundFont to Tone components

<img width="755" alt="image" src="https://user-images.githubusercontent.com/6765023/195110147-15d7ce66-1987-44cd-9d9b-44483aa66cce.png">

**Comment by brickhawkins** [comment]
Thanks for the reply, sorry didnt notice this issue has been replied
