### ISSUE TITLE
Not working in IL2CPP

### ISSUE THREAD

**Issue by MatheusMoura17** [homy-game-studio/hgs-unity-tone#4]
## Symptoms

Extremely slow audio. There are also too many memory allocations, possible bug during `MeltySynth` conversion to cpp.

**Comment by sinshu** [comment]
It's very nice to know that MeltySynth works on IL2CPP 😄
Was the bad thing for IL2CPP the `Vector<float>` version of `MultiplyAdd`?

**Comment by MatheusMoura17** [comment]
Hey @sinshu, tks for watch this issue!

Yes! After long time profiling an android device, i see `MemoryMarshal.Cast` and `Vector<float>` inside `MultiplyAdd` using 100% of cpu (Audio Thread) and too many GC alloc.

---

This solve the CPU Usage (main problem), but i still see lot of GC alloc in some parts. I will attach the profile results here later.
